import type { Metadata } from "next";
import "./globals.css";
import Navigation from "@/components/Navigation";


export const metadata: Metadata = {
  title: "Saleh",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body
        className={`antialiased h-full`}
      >
        <div className="min-h-full">
          <Navigation />
          <main>
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
